version: 1.0.0.{build}
environment:
  CODECOV_TOKEN:
    secure: rsFxWQLZS6IIliwfOn/YG3hnT/cgWPycvTqP2Ao6zkSlo0RGmCrlOv5H/O1Y0l8
build: false
install:
  - git submodule update --init
  - nuget install libgit2sharp -OutputDirectory .\packages -ExcludeVersion
  - ps: Install-Module Configuration -Minimum 1.0
build_script:
  - ps: .\Build.ps1 -Verbose
test_script:
  - ps: .\Test.ps1 # -Quiet
on_finish:
  - ps: .\Package.ps1 -Verbose | % { Push-AppveyorArtifact $_.FullName }
notifications:
  - provider: Slack
    auth_token:
      secure: 1S3E8mVpvHEpdXsgHot0Qc0yUnU8ka/yd6Kex7r7yIZmSPwkMDIJEvdf/WMMTb/g
    channel: poshcode
    template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}>\nCommit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:\n_{{commitMessage}}_{{#messages}}\n{{.}}{{/messages}}"